#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/Klee.h"
#include "images/Bomb.h"
#include "images/fish.h"
#include "images/Opening.h"
#include "images/water.h"
#include "images/Jean.h"

// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  DRAWSTART,
  START,
  PLAYINIT,
  PLAY,
  DRAWWIN,
  WIN,
  DRAWLOSE,
  LOSE,
} gba_state;

//define global constant might used later
const int KleeHeight = KLEE1721_HEIGHT;
const int KleeWidth = KLEE1721_WIDTH;
const int BombHeight = BOMB1617_HEIGHT;
const int BombWidth = BOMB1617_WIDTH;
const int fishHeight = FISHPNG_HEIGHT;
const int fishWidth = FISHPNG_WIDTH;
const int winning = 4;

const int fishCount = 8;

const int bombRange = 3;

const int Life = 1;

void infoDisplay(void) {
  char infoDisplay[] = "Fish Caught: ";
  drawString(12, 85, infoDisplay, ORANGE);
}

void scoreDisplay(int score) {
  char number[3];
  sprintf(number, "%d", score);
  drawString(25, 119, number, WHITE);
}

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = DRAWSTART;

  struct BombS bombInit = { 120, 40, 3 };
  struct KleeS KleeInit = { 0, 0, 1 };

  int effectiveness = 0;
  int maxspeed = 2;
  int KleeSpeed = 2;

  struct BombS *bomb1 = &bombInit;
  struct KleeS *Klee1 = &KleeInit;
  struct fishS fishs[fishCount];
  for (int i = 0; i < fishCount; i++) {
    fishs[i].rowF = randint(0, HEIGHT - fishHeight);
    fishs[i].colF = randint(0, WIDTH - fishWidth);
    fishs[i].rd = randint(1, 2);
    fishs[i].cd = randint(1, 2);
}

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    waitForVBlank();
    switch (state) {
      case DRAWSTART:
        drawFullScreenImageDMA(Opening);
        drawRectDMA(73, 15, 210, 60, YELLOW);
        drawCenteredString(10, 0, WIDTH, HEIGHT, "Welcome to Starfell Lake!", ORANGE);
        int score = 0;
        Klee1->life = Life;
        Klee1->rowK = HEIGHT/2;
        Klee1->colK = WIDTH/2;
        effectiveness = 0;
        maxspeed = 1;

        state = START;
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = DRAWSTART;
        }
        break;

      case START:
        drawCenteredString(40, 0, WIDTH, HEIGHT, "press START to BLAST fish", RED);

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
        state = PLAYINIT;

        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = DRAWSTART;
        }
        break;

      case PLAYINIT:
        waitForVBlank();
        fillScreenDMA(BLACK);

        infoDisplay();
        scoreDisplay(0);
        state = PLAY;
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = DRAWSTART;
        }
        break;

      case PLAY:
        for (int i = 0; i < fishCount; i++) {
          drawImageDMA(fishs[i].rowF, fishs[i].colF, fishWidth, fishHeight, fishpng);
        }
          //putting bomb
          //fish countering bomb

          for (int i = 0; i < fishCount; i++) {
            //if fish meet the bomb
            if ((fishs[i].colF + fishWidth)>bomb1->colB && fishs[i].colF < (bomb1->colB)+BombWidth
              && (fishs[i].rowF + fishHeight)>bomb1->rowB && fishs[i].rowF < (bomb1->rowB)+BombHeight && effectiveness) {
                  //erase fish and bomb
                  drawRectDMA(bomb1->rowB, bomb1->colB, BombWidth, BombHeight, BLACK);
                  drawRectDMA(fishs[i].rowF, fishs[i].colF, fishWidth, fishHeight, BLACK);
                  //draw Klee if she is erasedwait
                  drawImageDMA(Klee1->rowK, Klee1->colK, KleeWidth, KleeHeight, Klee1721);
                  //add one to the score
                  score += 1;
                  maxspeed += 1;
                  fishs[i].rd = - fishs[i].rd;
                  fishs[i].cd = - fishs[i].cd;
                  effectiveness = 0;
                  scoreDisplay(score);
                  //if Klee is also in the bombRange
                  if ((Klee1->colK + KleeWidth)>(bomb1->colB) && (Klee1->colK) < (bomb1->colB) + BombWidth
                  && (Klee1->rowK + KleeHeight)>(bomb1->rowB) && Klee1->rowK < (bomb1->rowB)+BombHeight) {
                      Klee1->life -= 1;
                    }
              }
            //if fish is still alive
            //erase the old fish
            drawRectDMA(fishs[i].rowF, fishs[i].colF, fishWidth, fishHeight, BLACK);
            //redrawKlee if she is erased
            drawImageDMA(Klee1->rowK, Klee1->colK, KleeWidth, KleeHeight, Klee1721);
            //move the fish
            if (fishs[i].colF <= 0)
                fishs[i].cd = randint(1,maxspeed);
            if (fishs[i].colF + fishWidth >= WIDTH)
                fishs[i].cd = -(randint(1,maxspeed));
            if (fishs[i].rowF <= 0)
                fishs[i].rd = (randint(1,maxspeed));
            if (fishs[i].rowF + fishHeight >= HEIGHT)
                fishs[i].rd = -(randint(1,maxspeed));

            fishs[i].rowF += fishs[i].rd;
            fishs[i].colF += fishs[i].cd;
            //draw the new fish
            drawImageDMA((fishs[i]).rowF, (fishs[i]).colF, fishWidth, fishHeight, fishpng);
            infoDisplay();
            scoreDisplay(score);
          }

          //Klee's move
          int oldKleeCol = Klee1->colK;
          int oldKleeRow = Klee1->rowK;
          if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
            if(oldKleeCol < (WIDTH - KleeWidth)) {
              Klee1->colK += KleeSpeed;
            }
          }
          if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
            if(oldKleeCol > 0) {
              Klee1->colK += -KleeSpeed;
            }
          }
          if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
            if(oldKleeRow < HEIGHT - KleeHeight) {
              Klee1->rowK += KleeSpeed;
            }
          }
          if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
            if(oldKleeRow > 0) {
              Klee1->rowK += -KleeSpeed;
            }
          }

          int oldBombCol = bomb1 -> colB;
          int oldBombRow = bomb1 -> rowB;
          if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
              //set new bomb
              bomb1 -> rowB = oldKleeRow;
              bomb1 -> colB = oldKleeCol;
              effectiveness = 1;
              drawRectDMA(oldBombRow, oldBombCol, BombWidth, BombHeight, BLACK);
          }

          drawRectDMA(oldKleeRow, oldKleeCol, KleeWidth, KleeHeight, BLACK);
          if(effectiveness){
          drawImageDMA(bomb1->rowB, bomb1->colB, BombWidth, BombHeight, Bomb1617);
          }
          drawImageDMA(Klee1->rowK, Klee1->colK, KleeWidth, KleeHeight, Klee1721);
          infoDisplay();
          scoreDisplay(score);

        if (score >= winning) {
          state = DRAWWIN;
        } else if (Klee1->life <= 0) {
          state = DRAWLOSE;
        }

        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = DRAWSTART;
        }

        break;

      case DRAWWIN:
        drawFullScreenImageDMA(water);
        drawCenteredString(0, 0, WIDTH, HEIGHT, "Mondstadt Grilled Fish for Dinner!", BLUE);
        state = WIN;
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = DRAWSTART;
        }
        break;

      case WIN:
        drawCenteredString(40, 0, WIDTH, HEIGHT, "Press START to Blast more fish!", WHITE);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = DRAWSTART;}
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            state = DRAWSTART;
        }
        break;

      case DRAWLOSE:
        drawFullScreenImageDMA(Jean);
        drawRectDMA(70, 13, 220, 60, BLUE);
        drawRectDMA(73, 10, 220, 60, CYAN);
        drawCenteredString(10, 0, WIDTH, HEIGHT, "Confinement Room?", RED);
        state = LOSE;
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = DRAWSTART;
        }
        break;

      case LOSE:
        drawCenteredString(40, 0, WIDTH, HEIGHT, "press START to sneak out", BLUE);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = DRAWSTART;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = DRAWSTART;
        }

        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}
